import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import WelcomeDialog from "@/components/WelcomeDialog";
import { Toaster } from "@/components/ui/sonner";
import AboutDialog from "@/components/AboutDialog";
import FeedbackDialog from "@/components/FeedbackDialog";
import { CSPostHogProvider } from "@/components/PostHog";

const comic_neue = Comic_Neue({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comic_neue.className}>
        <CSPostHogProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="p-8 min-h-dvh flex flex-col" >
              {children}

              <div className="grow"> </div>
              <div className="text-neutral-500 dark:text-neutral-400 flex gap-8">
                <AboutDialog />
                <FeedbackDialog />
              </div>

            </div>

            <WelcomeDialog />
          </ThemeProvider>
        </CSPostHogProvider>
        <Toaster />
      </body>
    </html>
  );
}
