import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"

import "./globals.css";

const comic_neue = Comic_Neue({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comic_neue.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
