import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import WelcomeDialog from "@/components/WelcomeDialog";

const comic_neue = Comic_Neue({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comic_neue.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          <WelcomeDialog />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
